import type { Metadata } from 'next'
import './globals.css'
import ChatBot from '@/components/ChatBot'

export const metadata: Metadata = {
  title: 'TalkBetter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-[#242323] w-full h-screen flex'>
        {children}
        <ChatBot />
      </body>
    </html>
  )
}
